# Generated by Django 3.2.15 on 2022-09-07 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('EDUCATION', 'Education'), ('HOME', 'Home'), ('TRAVEL', 'Travel'), ('CLOTHING', 'Clothing'), ('FOOD', 'Food'), ('SAVINGS', 'Savings'), ('ENTERTAINMENT', 'Entertainment')], default='HOME', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budget.budget'),
        ),
    ]
